AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "A template to create all the Event Processing infrastructure."

Parameters:
  CodeSigningConfigArn:
    Type: String
    Default: "none"
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
    ConstraintDescription: must be dev, build, staging, integration or production

Conditions:
  SetPermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  isProductionOrStaging: !Or [!Equals [ !Ref environment, production], !Equals [ !Ref environment, staging], !Equals [ !Ref environment, integration]]

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - SetPermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Architectures:
      - x86_64

Mappings:
  AuditAccountARN:
    Environment:
      staging: "arn:aws:iam::778587367904:root"
      build: "arn:aws:iam::761029721660:root"
      dev: "arn:aws:iam::725018305812:root"
  KBVQueueARN:
    Environment:
      staging: "arn:aws:sqs:eu-west-2:<AccountId>:root"
      build: ""
      dev: ""
  IPVQueueARN:
    Environment:
      staging: "arn:aws:sqs:eu-west-2:<AccountId>:root"
      build: ""
      dev: ""
  SPOTQueueARN:
    Environment:
      staging: "arn:aws:sqs:eu-west-2:<AccountId>:root"
      build: ""
      dev: ""

Resources:
  epSNSTopic:
    Properties:
      TopicName: !Sub
        - "EventProcessorSNSTopic-${EnvironmentName}"
        - EnvironmentName: !Ref Environment
    Type: "AWS::SNS::Topic"

  SNSSubscribePolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SNSSubscribePolicy
        Version: 2012-10-17
        Statement:
          - Sid: SNSSubscribePolicy-1
            Effect: Allow
            Action:
              - 'sns:Subscribe'
            Principal:
              AWS:
                - !FindInMap [AuditAccountARN, Environment, !Ref Environment]
            Resource: !Ref epSNSTopic
      Topics:
      - !Ref epSNSTopic

  SQSPublishPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref KBVLambdaSQSAccessRole
        - !Ref IPVLambdaSQSAccessRole
        - !Ref SPOTLambdaSQSAccessRole
      PolicyName: sqs_publish_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sns:Publish'
            Resource: !Sub
              - 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:{topicName}'
              - topicName: !GetAtt epSNSTopic.TopicName

  KBVEventProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/EventProcessorFunction-KBV"

  KBVEventProcessorFunction:
    DependsOn:
      - KBVEventProcessorLogGroup
      - KBVLambdaAccessRole
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "EventProcessorFunction-KBV"
      CodeUri: ../event-processing/event-processor
      PackageType: Zip
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !GetAtt KBVLambdaAccessRole.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts

  KBVEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref KBVEventProcessorFunction
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 2
      DestinationConfig:
        OnSuccess:
          Destination: !Ref epSNSTopic

  KBVEventProcessorUnknownFieldsErrorMetric:
    DependsOn:
      - KBVEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "WARN UNKNOWN FIELDS"
      LogGroupName: "/aws/lambda/EventProcessorFunction-KBV"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Unknown Fields KBV"

  KBVEventProcessorUnknownFieldsAlarm:
    DependsOn:
      - KBVEventProcessorUnknownFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "KBV Event Processor Unknown Fields Alarm"
      AlarmName: "UnknownFieldsAlarm-KBV"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Unknown Fields KBV"
      Namespace: "lambda/di/txma/errors"

  KBVEventProcessorRequiredFieldsErrorMetric:
    DependsOn:
      - KBVEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "ERROR VALIDATION ERROR"
      LogGroupName: "/aws/lambda/EventProcessorFunction-KBV"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Validation Errors KBV"

  KBVEventProcessorRequiredFieldsAlarm:
    DependsOn:
      - EventProcessorRequiredFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "KBV Event Processor Required Fields Alarm"
      AlarmName: "RequiredFieldsAlarm-KBV"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Validation Errors KBV"
      Namespace: "lambda/di/txma/errors"

  KBVLambdaAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LambdaAccessRole-KBV"
      PermissionsBoundary: !If
        - SetPermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"

  KBVLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: isProductionOrStaging
    Properties:
      EventSourceArn: !Ref KBVQueueARN
      FunctionName: !GetAtt KBVEventProcessorFunction.Arn

  IPVEventProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/EventProcessorFunction-IPV"

  IPVEventProcessorFunction:
    DependsOn:
      - IPVEventProcessorLogGroup
      - IPVLambdaAccessRole
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "EventProcessorFunction-IPV"
      CodeUri: ../event-processing/event-processor
      PackageType: Zip
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !GetAtt IPVLambdaAccessRole.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  IPVEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref IPVEventProcessorFunction
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 2
      DestinationConfig:
        OnSuccess:
          Destination: !Ref epSNSTopic

  IPVEventProcessorUnknownFieldsErrorMetric:
    DependsOn:
      - IPVEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "WARN UNKNOWN FIELDS"
      LogGroupName: "/aws/lambda/EventProcessorFunction-IPV"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Unknown Fields IPV"

  IPVEventProcessorUnknownFieldsAlarm:
    DependsOn:
      - IPVEventProcessorUnknownFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "IPV Event Processor Unknown Fields Alarm"
      AlarmName: "UnknownFieldsAlarm-IPV"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Unknown Fields IPV"
      Namespace: "lambda/di/txma/errors"

  IPVEventProcessorRequiredFieldsErrorMetric:
    DependsOn:
      - IPVEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "ERROR VALIDATION ERROR"
      LogGroupName: "/aws/lambda/EventProcessorFunction-IPV"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Validation Errors IPV"

  IPVEventProcessorRequiredFieldsAlarm:
    DependsOn:
      - EventProcessorRequiredFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "IPV Event Processor Required Fields Alarm"
      AlarmName: "RequiredFieldsAlarm-IPV"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Validation Errors IPV"
      Namespace: "lambda/di/txma/errors"

  IPVLambdaAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LambdaAccessRole-IPV"
      PermissionsBoundary: !If
        - SetPermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"

  IPVLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: isProductionOrStaging
    Properties:
      EventSourceArn: !Ref IPVQueueARN
      FunctionName: !GetAtt IPVEventProcessorFunction.Arn

  SPOTEventProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/EventProcessorFunction-SPOT"

  SPOTEventProcessorFunction:
    DependsOn:
      - SPOTEventProcessorLogGroup
      - SPOTLambdaAccessRole
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "EventProcessorFunction-SPOT"
      CodeUri: ../event-processing/event-processor
      PackageType: Zip
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !GetAtt SPOTLambdaAccessRole.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  SPOTEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref SPOTEventProcessorFunction
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 2
      DestinationConfig:
        OnSuccess:
          Destination: !Ref epSNSTopic

  SPOTEventProcessorUnknownFieldsErrorMetric:
    DependsOn:
      - SPOTEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "WARN UNKNOWN FIELDS"
      LogGroupName: "/aws/lambda/EventProcessorFunction-SPOT"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Unknown Fields SPOT"

  SPOTEventProcessorUnknownFieldsAlarm:
    DependsOn:
      - SPOTEventProcessorUnknownFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "SPOT Event Processor Unknown Fields Alarm"
      AlarmName: "UnknownFieldsAlarm-SPOT"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Unknown Fields SPOT"
      Namespace: "lambda/di/txma/errors"

  SPOTEventProcessorRequiredFieldsErrorMetric:
    DependsOn:
      - SPOTEventProcessorFunction
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "ERROR VALIDATION ERROR"
      LogGroupName: "/aws/lambda/EventProcessorFunction-SPOT"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "lambda/di/txma/errors"
          MetricName: "Validation Errors SPOT"

  SPOTEventProcessorRequiredFieldsAlarm:
    DependsOn:
      - EventProcessorRequiredFieldsErrorMetric
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "SPOT Event Processor Required Fields Alarm"
      AlarmName: "RequiredFieldsAlarm-SPOT"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Statistic: Sum
      Period: 86400
      Threshold: 1
      MetricName: "Validation Errors SPOT"
      Namespace: "lambda/di/txma/errors"

  SPOTLambdaAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "LambdaAccessRole-SPOT"
      PermissionsBoundary: !If
        - SetPermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"

  SPOTLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: isProductionOrStaging
    Properties:
      EventSourceArn: !Ref SPOTQueueARN
      FunctionName: !GetAtt SPOTEventProcessorFunction.Arn
