version=0.1
[default.build.parameters]
beta_features = true

[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "di-txma-audit-develop"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"develop\""
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[dev.deploy.parameters]
stack_name = "di-txma-audit-develop"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"develop\""
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[build.deploy.parameters]
stack_name = "di-txma-audit-build"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"build\""
parameter_overrides=[
    "Environment=build"
]

[staging.deploy.parameters]
stack_name = "di-txma-audit-staging"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"staging\""
parameter_overrides=[
    "Environment=staging"
]

[production.deploy.parameters]
stack_name = "di-txma-audit-production"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"production\""
parameter_overrides=[
    "Environment=production"
]

[integration.deploy.parameters]
stack_name = "di-txma-audit-integration"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
tags = "project=\"di-txma-audit\" stage=\"integration\""
parameter_overrides=[
    "Environment=integration"
]