version=0.1
[default.build.parameters]
beta_features = true

[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "di-txma-event-processing-develop"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"develop\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=develop"
]

[develop.deploy.parameters]
stack_name = "di-txma-event-processing-develop"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"develop\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=develop"
]

[build.deploy.parameters]
stack_name = "di-txma-event-processing-build"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"build\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=build"
]

[staging.deploy.parameters]
stack_name = "di-txma-event-processing-staging"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"staging\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=staging"
]

[production.deploy.parameters]
stack_name = "di-txma-event-processing-production"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"production\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=production"
]

[integration.deploy.parameters]
stack_name = "di-txma-event-processing-integration"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"integration\""
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "Environment=integration"
]